language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services: mongodb
deploy:
  provider: lambda
  function_name: "quote-api"
  region: "us-east-2"
  role: "arn:aws:iam::654673036772:role/lambda-basic"
  runtime: "nodejs12.x"
  handler_name: "handler"
  timeout: 10
  env:
    NODE_ENV=production
